### ISSUE TITLE
Dropdown menu not dropping down

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/engagement-lab-website#20]
Clickable but cannot go to any of the projects or publications category groups - only all

<img width="571" alt="screen shot 2017-05-29 at 11 15 13 am" src="https://cloud.githubusercontent.com/assets/11821504/26556395/3ebf3ee2-4468-11e7-8ed9-8f1e4446fda8.png">

**Comment by jpailthorpe** [comment]
not sure what you mean here (unless you already fixed it) as it works for me. Maybe worth removing these content blocks entirely though, as they seem a bit arbitrary now maybe?

**Comment by esalling23** [comment]
It refuses to work for me - not sure why but if it's only me then it's not priority
